DROP TABLE EX;
CREATE TABLE EX (
    EX_NO NUMBER NOT NULL PRIMARY KEY,
    EX_CONTENT VARCHAR2(100 BYTE) NOT NULL,
    EX_CREATED_AT TIMESTAMP
);

DROP SEQUENCE EX_SEQ;
CREATE SEQUENCE EX_SEQ NOCACHE;

INSERT INTO EX VALUES(EX_SEQ.NEXTVAL, '수요일', SYSTIMESTAMP);
INSERT INTO EX VALUES(EX_SEQ.NEXTVAL, '목요일', SYSTIMESTAMP);
INSERT INTO EX VALUES(EX_SEQ.NEXTVAL, '금요일', SYSTIMESTAMP);